apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy
  namespace: cluster-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort