crds:
  enabled: true

prometheus:
  enabled: false

extraArgs:
  - --cluster-resource-namespace=cluster-system

config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true
