crds:
  enabled: true

prometheus:
  enabled: false

extraArgs:
  - --cluster-resource-namespace=cluster-system

config:
  enableGatewayAPI: true
  enableGatewayAPIListenerSet: true
  featureGates:
    ListenerSets: true
