#!/bin/bash
clustername=${1:kind}
containers=$(docker ps -f "name=$clustername-worker" --format '{{.Names}}')
gateway=$(docker network inspect kind --format '{{ (index .IPAM.Config 
0).Gateway }}')
if [ -z "$containers" ]; then
  echo "No kind cluster containers found with name prefix '$clustername-'"
  exit 1
else
  echo "Stopping kind cluster worker containers with name prefix '$clustername-'"
  counter=1
  for container in $containers; do
    echo "Stopping container: $container"
    docker stop "$container"
    echo "Disconnecting container: $container from network 'kind'"
    docker network disconnect kind "$container"
    ip=$gateway$((counter++))
    echo "Reconnecting container: $container to network 'kind' with IP '$ip'"
    docker network connect --ip "$ip" kind "$container"
  done
  for container in $containers; do
    echo "Starting container: $container"
    docker start "$container"
  done
  echo "All worker containers with prefix '$clustername-' have been restarted."
fi
