httpRoute:
  enabled: true
  parentRefs:
    - name: headlamp-listenerset
      group: gateway.networking.k8s.io
      kind: ListenerSet
      sectionName: https
  hostnames:
    - headlamp
  
config:
  inCluster: true
  inClusterContextName: "local-devcluster"
