ingress:
  enabled: false
  annotations:
    cert-manager.io/cluster-issuer: local-ca
  hosts:
    - host: headlamp
      paths:
        - path: /
          type: ImplementationSpecific
  tls:
    - secretName: headlamp
      hosts:
        - headlamp

httpRoute:
  enabled: true
  parentRefs:
    - name: cluster-envoygateway
  hostnames:
    - headlamp.k8s.local
  
config:
  inCluster: true
  inClusterContextName: "local-devcluster"
