ingress:
  enabled: false
  annotations:
    cert-manager.io/cluster-issuer: local-ca
  hosts:
    - host: headlamp.k8s.local
      paths:
        - path: /
          type: ImplementationSpecific
  tls:
    - secretName: headlamp
      hosts:
        - headlamp.k8s.local

httpRoute:
  enabled: true
  parentRefs:
    - name: cluster-envoygateway
      group: gateway.networking.k8s.io
      kind: Gateway
      sectionName: https
  hostnames:
    - headlamp.k8s.local
  
config:
  inCluster: true
  inClusterContextName: "local-devcluster"
