kind: ListenerSet
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: headlamp-listenerset
  namespace: cluster-system
  annotations:
    cert-manager.io/cluster-issuer: local-ca
spec:
  parentRef:
    name: cluster-envoygateway
    namespace: cluster-system
  listeners:
    - name: https
      hostname: headlamp
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: headlamp-https
            kind: Secret
