apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: cluster-system
  annotations:
    # networking.istio.io/service-type: NodePort
spec:
  gatewayClassName: istio
  listeners:
    - name: default-http
      hostname: "k8sdash"
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
